### ISSUE TITLE
Please support Kube2IAM auth, instead of cred file

### ISSUE THREAD

**Issue by AceHack** [triggermesh/knative-lambda-sources#27]
I would like to use the credentials built into the POD via Kube2IAM instead of cred file

**Comment by sebgoa** [comment]
For which source in particular ?

**Comment by sebgoa** [comment]
Never tried but we could check that the Pod has a the kube2iam annotation and if yes then not try to load the secrets.

Set an env var to read the annotation from the metadata:

```
        - name: MY_POD_ANNOTATION
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotation
```

and that in the pod template:

```
spec:
...
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: TEST_ROLE_NAME
```
